"""preprints table

Revision ID: 9e16d9b795a9
Revises: 
Create Date: 2025-02-02 21:04:04.364829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e16d9b795a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(length=140), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('preprint_id_per_year', sa.Integer(), nullable=False),
    sa.Column('preprint_id', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preprints_authors'), ['authors'], unique=False)
        batch_op.create_index(batch_op.f('ix_preprints_preprint_id'), ['preprint_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_preprints_preprint_id_per_year'), ['preprint_id_per_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_preprints_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_preprints_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preprints_title'))
        batch_op.drop_index(batch_op.f('ix_preprints_timestamp'))
        batch_op.drop_index(batch_op.f('ix_preprints_preprint_id_per_year'))
        batch_op.drop_index(batch_op.f('ix_preprints_preprint_id'))
        batch_op.drop_index(batch_op.f('ix_preprints_authors'))

    op.drop_table('preprints')
    # ### end Alembic commands ###
